//html questions here.
//

const qstnAns = [
    {
      id: "001",
      question: "HTML stands for",
      a: "HyperText Machine Language",
      b: "HyperText and links Markup Language",
      c: "HyperText Markup Language",
      d: "None of these",
      answer: "c",
    },
    {
      id: "002",
      question: "The correct sequence of HTML tags for starting a webpage is",
      a: "Head, Title, HTML, body",
      b: "HTML, Body, Title, Head",
      c: "HTML, Head, Title, Body",
      d: "HTML, Head, Title, Body",
      answer: "d",
    },
    {
      id: "003",
      question: " Which of the following element is responsible for making the text bold in HTML?",
      a: "<pre>",
      b: "<a>",
      c: "<b>",
      d: "<br>",
      answer: "c",
    },
    {
      id: "004",
      question: " Which of the following tag is used for inserting the largest heading in HTML?",
      a: "<h3>",
      b: "<h1>",
      c: "<h5>",
      d: "<h6>",
      answer: "b",
    },
    {
      id: "005",
      question: " Which of the following tag is used to insert a line-break in HTML?",
       a:"<br>",
       b:"<a>",
       c:"<pre>",
       d:"<b>",
      answer: "a",
    },
    {
      id: "006",
      question: "How to create an unordered list (a list with the list items in bullets) in HTML?",
      a: "<ul>",
      b: "<ol>",
      c: "<li>",
      d: "<i>",
      answer: "a",
    },
    {
      id: "007",
      question: "How to create an ordered list (a list with the list items in numbers) in HTML?",
      a: "<ul>",
      b: "<ol>",
      c: "<li>",
      d: "<i>",
      answer: "b",
    },
    {
      id: "008",
      question: "Which of the following element is responsible for making the text italic in HTML?",
      a: "<i>",
      b: "<italic>",
      c: "<it>",
      d: "<pre>",
      answer: "a",
    },
    {
      id: "009",
      question: "<input> is -",
      a: "a format tag.",
      b: "an empty tag.",
      c: "All of the above",
      d: "None of the above",
      answer: "b",
    },
    {
      id: "010",
      question: " Which of the following tag is used to make the underlined text?",
      a: "<i>",
      b: "<ul>",
      c: "<u>",
      d: "<pre>",
      answer: "c",
    },
  
    // css questions here.
  
    {
      id: "011",
      question: " CSS stands for",
      a: "Cascade style sheets",
      b: "Color and style sheets",
      c: "Cascading style sheets",
      d: "None of the above",
      answer: "c",
    },
    {
      id: "012",
      question: "The property in CSS used to change the background color of an element is -",
      a: "bgcolor",
      b: "color",
      c: "background-color",
      d: "All of the above",
      answer: "c",
    },
    {
      id: "013",
      question: "The CSS property used to control the element's font-size is -",
      a: "text-style",
      b: "text-size",
      c: "font-size",
      d: "None of the above",
      answer: "c",
    },
    {
      id: "014",
      question: "The HTML attribute used to define the inline styles is -",
      a: "style",
      b: "styles",
      c: "class",
      d: "None of the above",
      answer: "a",
    },
    {
      id: "015",
      question: "he HTML attribute used to define the internal stylesheet is -",
      a: "<style>",
      b: "style",
      c: "<link>",
      d: "<script>",
      answer: "a",
    },
    {
      id: "016",
      question: "Which of the following CSS property is used to set the background image of an element?",
      a: "background-attachment",
      b: "background-image",
      c: "background-color",
      d: "None of the above",
      answer: "b",
    },
    {
      id: "017",
      question: " Which of the following is the correct syntax to make the background-color of all paragraph elements to yellow?",
      a: "p {background-color : yellow;}",
      b: "p {background-color : #yellow;}",
      c: "all {background-color : yellow;}",
      d: "all p {background-color : #yellow;}",
      answer: "a",
    },
    {
      id: "018",
      question: "Which of the following is the correct syntax to display the hyperlinks without any underline?",
      a: "a {text-decoration : underline;}",
      b: "a {decoration : no-underline;}",
      c: "a {text-decoration : none;}",
      d: "None of the above",
      answer: "c",
    },
    {
      id: "019",
      question: "Which of the following property is used as the shorthand property for the padding properties?",
       a:"padding-left",
       b:"padding-right",
       c:"padding",
       d:"All of the above",
       answer: "c",
    },
    {
      id: "020",
      question: "The CSS property used to make the text bold is -",
      a: "font-weight : bold",
      b: "weight: bold",
      c: "font: bold",
      d: "style: bold",
      answer: "a",
    },
    // javascript mcq qustions here.
  
  
    {
      id: "021",
      question: "Which type of JavaScript language is ___",
      a: "Object-Oriented",
      b: "Object-Based",
      c: "Assembly-language",
      d: "High-level",
      answer: "b",
    },
    {
      id: "022",
      question: " Which one of the following also known as Conditional Expression:",
      a: "Alternative to if-else",
      b: "Switch statement",
      c: "If-then-else statement",
      d: "immediate if",
      answer: "d",
    },
    {
      id: "023",
      question: "In JavaScript, what is a block of statement?",
      a: "Conditional block",
      b: "block that combines a number of statements into a single compound statement",
      c: "both conditional block and a single statement",
      d: "block that contains a single statement",
      answer: "b",
    },
    {
      id: "024",
      question: "When interpreter encounters an empty statements, what it will do:",
      a: "Shows a warning",
      b: "Prompts to complete the statement",
      c: "Throws an error",
      d: "Ignores the statements",
      answer: "d",
    },
    {
      id: "025",
      question: " Which of the following variables takes precedence over the others if the names are the same?",
      a: "Global variable",
      b: "The local element",
      c: "The two of the above",
      d: "None of the above",
      answer: "b",
    },
    {
      id: "026",
      question: "Which one of the following is the correct way for calling the JavaScript co",
      a: "Preprocessor",
      b: "Triggering Event",
      c: "RMI",
      d: "Function/Method",
      answer: "d",
    },
    {
      id: "027",
      question: "Which of the following type of a variable is volatile?",
      a: "Mutable variable",
      b: "Dynamic variable",
      c: "Volatile variable",
      d: "Immutable variable",
      answer: "a",
    },
    {
      id: "028",
      question: " Which of the following option is used as hexadecimal literal beginning?",
      a: "00",
      b: "0x",
      c: "0X",
      d: "Both 0x and 0X",
      answer: "d",
    },
    {
      id: "029",
      question: "When there is an indefinite or an infinite value during an arithmetic computation in a program, then JavaScript prints______.",
      a: "Prints an excepion erro",
      b: "Prints an overlow erro",
      c: "Displays Infinity",
      d: "Prints the vale as suc",
      answer: "c",
    },
    {
      id: "030",
      question: "In the JavaScript, which one of the following is not considered as an error:",
      a: "Syntax error",
      b: "Missing of semicolons",
      c: "Division by zero",
      d: "Missing of Bracket",
      answer: "c",
    },
    // DSA mcq questions here..
  
  
    {
      id: "031",
      question: " How can we describe an array in the best possible way?",
      a: "The Array shows a hierarchical structure.",
      b: "Arrays are immutable.",
      c: "Container that stores the elements of similar types",
      d: "The Array is not a data structure",
      answer: "c",
    },
    {
      id: "032",
      question: "Which of the following is the correct way of declaring an array?",
      a: "int javatpoint[10];",
      b: "int javatpoint;",
      c: "javatpoint{20};",
      d: "array javatpoint[10];",
      answer: "a",
    },
    {
      id: "033",
      question: " How can we initialize an array in C language?",
      a: "int arr[2]=(10, 20)",
      b: "int arr(2)={10, 20}",
      c: "int arr[2] = {10, 20}",
      d: "int arr(2) = (10, 20)",
      answer: "c",
    },
    {
      id: "034",
      question: "Which of the following is the advantage of the array data structure?",
      a: "Elements of mixed data types can be stored.",
      b: "Easier to access the elements in an array",
      c: "Index of the first element starts from 1.",
      d: "Elements of an array cannot be sorted",
      answer: "b",
    },
    {
      id: "035",
      question: "Which of the following highly uses the concept of an array?",
      a: "Binary Search tree",
      b: "Caching",
      c: "Spatial locality",
      d: "Scheduling of Processes",
      answer: "c",
    },
    {
      id: "036",
      question: "Which of the following is the disadvantage of the array?",
      a: "Stack and Queue data structures can be implemented through an array.",
      b: "Index of the first element in an array can be negative",
      c: "Wastage of memory if the elements inserted in an array are lesser than the allocated size",
      d: "Elements can be accessed sequentially.",
      answer: "c",
    },
    {
      id: "037",
      question: " Which one of the following is the size of int arr[9] assuming that int is of 4 bytes?",
      a: "9",
      b: "36",
      c: "35",
      d: "None of the above",
      answer: "b",
    },
    {
      id: "038",
      question: "Which one of the following is the process of inserting an element in the stack?",
      a: "Insert",
      b: "Add",
      c: "Push",
      d: "None of the above",
      answer: "c",
    },
    {
      id: "039",
      question: "When the user tries to delete the element from the empty stack then the condition is said to be a ____",
      a: "Underflow",
      b: "Garbage collection",
      c: "Overflow",
      d: "None of the above",
      answer: "a",
    },    {
      id: "040",
      question: " If the size of the stack is 10 and we try to add the 11th element in the stack then the condition is known as___",
      a: "Underflow",
      b: "Garbage collection",
      c: "Overflow",
      d: "None of the above",
      answer: "c",
    },
   
  
  ];
  